deployment:
  image:
    name: debu99/helloworld
    tag: latest
  replicas: 1
  port: 3000
  env:
    ENV_KEY: ENV_VALUE
  resources:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 100Mi
service:
  type: ClusterIP
  port: 3000