
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
        imagePullPolicy: IfNotPresent
        {{- if .Values.deployment.env }}
        env:
        {{- range $key, $value := .Values.deployment.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
          protocol: TCP
        resources:
{{ toYaml .Values.deployment.resources | indent 10 }}
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /ping
            port: {{ .Values.deployment.port }}
        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /ping
            port: {{ .Values.deployment.port }}