---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.deployment.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP