name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches:
      - main
      - staging
    types:
      - completed

jobs:
  staging_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup Helm
        uses: Azure/setup-helm@v3
        with:
          version: 'v3.8.2'

      - name: check staging hotfix
        if: github.ref == 'refs/heads/staging' && (startsWith(github.head_ref, 'hotfix/') || contains(github.event.head_commit.message, '[hotfix]'))
        run: |
          echo "[INFO] Hotfix branch detected in staging"

      - name: check staging release
        if: github.ref == 'refs/heads/staging' && (startsWith(github.head_ref, 'release/') || contains(github.event.head_commit.message, '[release]'))
        run: |
          echo "[INFO] Release branch detected in staging"

      - name: Deploy to staging
        if: github.ref == 'refs/heads/staging' && !(startsWith(github.head_ref, 'hotfix/') || contains(github.event.head_commit.message, '[hotfix]')) && !(startsWith(github.head_ref, 'release/') || contains(github.event.head_commit.message, '[release]')) 
        run: |
          echo "[INFO] not Hotfix/Release branch"
          helm version
          #helm upgrade --install my-app-staging ./helm-chart -f ./helm-chart/values.staging.yaml

      - name: Smoke test
        env:
          APP_DOMAIN: "https://app.vic510.click"
          APP_PORT: "8000"
          APP_NAMESPACE: "dev"
          HEALTHCHECK_URL: '/health'
        run: |
          echo "staging smoke test"

  staging_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: 'prod'
    steps:
      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "[INFO] main branch detected"
          helm version
          #helm upgrade --install my-app-prod ./helm-chart -f ./helm-chart/values.prod.yaml

      - name: Smoke test
        env:
          APP_DOMAIN: "https://app.vic510.click"
          APP_PORT: "8000"
          APP_NAMESPACE: "dev"
          HEALTHCHECK_URL: '/health'
        run: |
          echo "prod smoke test"