name: CI

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.4
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
