name: K8s PR Sandbox Delete

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  kubernetes-delete:
    uses: debu99/reusable-workflows/.github/workflows/k8s-delete.yml@main
    with:
      PR_NAME: pr-${{ github.event.number }}
      KUBE_NAMESPACE: demo
    secrets:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
